[package]
name = "circuit_definitions"
version = "0.140.0-gpu-wrapper.0"
edition = "2021"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/era-zkevm_test_harness/"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
description = "ZKsync Era circuits definitions"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# zk_evm = {path = "../../zk_evm"}
# zkevm_circuits = {path = "../../zkevm_circuits", features = ["verbose_circuits"]}
# snark_wrapper = {path = "../../snark_wrapper"}

snark_wrapper = "=0.1.0"
zkevm_circuits = "=0.140.0"
zk_evm = "=0.140.0"

derivative = "2.2"
serde = {version = "1", features = ["derive"]}
crossbeam = "0.8"
seq-macro = "0.3.5"

[features]
default = []
log_tracing = ["zkevm_circuits/log_tracing"]
