name: "Rust CI"
on:
  pull_request:

jobs:
  build:
    name: cargo build and test
    runs-on: [ubuntu-22.04-github-hosted-32core]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Setup rust
        run: |
          rustup set profile minimal
          rustup toolchain install nightly-2023-08-23
          rustup default nightly-2023-08-23
          cargo install cargo-nextest 
      - run: |
          cargo build --verbose
          cd circuit_definitions && cargo build --verbose
          cd circuit_encodings && cargo build --verbose
          cd circuit_sequencer_api && cargo build --verbose
          cd kzg && cargo build --verbose


    test:
      name: cargo test
      runs-on: [ubuntu-22.04-github-hosted-32core]
      needs: build
      steps:
        - uses: actions/checkout@v3
        - uses: actions-rust-lang/setup-rust-toolchain@v1
          with:
            rustflags: ""
        - name: Setup rust
          run: |
            rustup set profile minimal
            rustup toolchain install nightly-2023-08-23
            rustup default nightly-2023-08-23
            cargo install cargo-nextest 
        - run: |
            cargo nextest run --release
            cd circuit_definitions && cargo nextest run --release
            cd circuit_encodings && cargo nextest run --release
            cd circuit_sequencer_api && cargo nextest run --release
            cd kzg && cargo nextest run --release

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
