name: "Rust CI"
on:
  pull_request:

jobs:
  build:
    name: cargo build and test
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Setup rust
        run: |
          rustup set profile minimal
          rustup toolchain install nightly-2023-08-23
          rustup default nightly-2023-08-23
      - run: cargo build --verbose
      - run: cargo test --verbose --all --no-run

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
